### ISSUE TITLE
Wrong entry in requirement.txt

### ISSUE THREAD

**Issue by imyashkale** [saydus/twitter-overlap#4]
`time` and `os` is the wrong entry in the requirement.txt

Its gives following error.
ERROR: Could not find a version that satisfies the requirement time (from -r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for time (from -r requirements.txt (line 3))

**Comment by saydus** [comment]
Will fix it today!

**Comment by saydus** [comment]
Thanks @imyashkale!
